# site settings
title: MIT Assistive Technology Club
subtitle: by HTML5 UP
email: assistive-technology-exec@mit.edu
description: Our mission is to make the world more accessible to everyone 
<br /> by building connections within our community and fostering 
<br /> collaborative efforts to create inclusive technology. Through AT@MIT, 
<br /> we introduce students to the fun (and challenging) design space of 
<br /> assistive technology while building connections between community members, 
<br /> engineers, and designers. We hope to inspire participants to pursue projects 
in the AT space in the future.
baseurl: "/at-club" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 77 Massachusetts Ave
city: Cambridge
state: MA
zip_code: 02139
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/MIT-Assistive-Technology
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/assistivetech_mit/
  LinkedIn: https://www.linkedin.com/company/mit-assistive-technology-club/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
